//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleLog
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsoleLog
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime ReportDate { get; set; }
        public string GMTDay { get; set; }
        public string GMTHours { get; set; }
        public string Increment { get; set; }
        public string PreparedByESL { get; set; }
        public string ShiftDescription { get; set; }
        public string OEC_OECLead { get; set; }
        public string OEC_ESL { get; set; }
        public string OEC_ESC { get; set; }
        public string OEC_FPL { get; set; }
        public string OEC_OPR { get; set; }
        public string ROBO_Lead { get; set; }
        public string ROBO_Systems { get; set; }
        public string ROBO_Task { get; set; }
        public string EVR { get; set; }
        public string IPCanada { get; set; }
        public string ShiftSummary { get; set; }
        public string ForwardOrOpenWork { get; set; }
        public string MSSStart_RWS_Lab { get; set; }
        public string MSSStart_RWS_Cup { get; set; }
        public Nullable<int> MSSStart_MT_WS { get; set; }
        public string MSSStart_SSRMS_BasedOn_LEE { get; set; }
        public string MSSStart_SPDM_BasedOn { get; set; }
        public string MSSStart_FSTStates_MBS { get; set; }
        public string MSSStart_FSTStates_POA { get; set; }
        public string MSSStart_FSTStates_SSRMS { get; set; }
        public string MSSStart_FSTStates_SPDMPSU { get; set; }
        public string MSSStart_FSTStates_SPDMBody { get; set; }
        public string MSSStart_FSTStates_SPDMSACU { get; set; }
        public string MSSStart_FSTStates_SPDMArms { get; set; }
        public string MSSStart_Payloads_SSRMSTipLee { get; set; }
        public string MSSStart_Payloads_SPDMLee { get; set; }
        public string MSSStart_Payloads_OTCM1 { get; set; }
        public string MSSStart_Payloads_OTCM2 { get; set; }
        public string MSSStart_Payloads_MCAS { get; set; }
        public string MSSStart_Payloads_EOTP { get; set; }
        public string MSSStart_Payloads_POA { get; set; }
        public string MSSStart_SSRMSConfiguration { get; set; }
        public string MSSStart_SPDMConfiguration { get; set; }
        public Nullable<decimal> MSSStart_Joints_SSRMS_SR { get; set; }
        public Nullable<decimal> MSSStart_Joints_SSRMS_SY { get; set; }
        public Nullable<decimal> MSSStart_Joints_SSRMS_SP { get; set; }
        public Nullable<decimal> MSSStart_Joints_SSRMS_EP { get; set; }
        public Nullable<decimal> MSSStart_Joints_SSRMS_WP { get; set; }
        public Nullable<decimal> MSSStart_Joints_SSRMS_WY { get; set; }
        public Nullable<decimal> MSSStart_Joints_SSRMS_WR { get; set; }
        public Nullable<decimal> MSSStart_Joints_SSRMS_SPDMBR { get; set; }
        public Nullable<decimal> MSSStart_Joints_ARM1_SR { get; set; }
        public Nullable<decimal> MSSStart_Joints_ARM1_SY { get; set; }
        public Nullable<decimal> MSSStart_Joints_ARM1_SP { get; set; }
        public Nullable<decimal> MSSStart_Joints_ARM1_EP { get; set; }
        public Nullable<decimal> MSSStart_Joints_ARM1_WP { get; set; }
        public Nullable<decimal> MSSStart_Joints_ARM1_WY { get; set; }
        public Nullable<decimal> MSSStart_Joints_ARM1_WR { get; set; }
        public Nullable<decimal> MSSStart_Joints_ARM2_SR { get; set; }
        public Nullable<decimal> MSSStart_Joints_ARM2_SY { get; set; }
        public Nullable<decimal> MSSStart_Joints_ARM2_SP { get; set; }
        public Nullable<decimal> MSSStart_Joints_ARM2_EP { get; set; }
        public Nullable<decimal> MSSStart_Joints_ARM2_WP { get; set; }
        public Nullable<decimal> MSSStart_Joints_ARM2_WY { get; set; }
        public Nullable<decimal> MSSStart_Joints_ARM2_WR { get; set; }
        public Nullable<decimal> MSSStart_Joints_EOTP { get; set; }
        public string MSSEnd_RWS_Lab { get; set; }
        public string MSSEnd_RWS_Cup { get; set; }
        public Nullable<int> MSSEnd_MT_WS { get; set; }
        public string MSSEnd_SSRMS_BasedOn_LEE { get; set; }
        public string MSSEnd_SPDM_BasedOn { get; set; }
        public string MSSEnd_FSTStates_MBS { get; set; }
        public string MSSEnd_FSTStates_POA { get; set; }
        public string MSSEnd_FSTStates_SSRMS { get; set; }
        public string MSSEnd_FSTStates_SPDMPSU { get; set; }
        public string MSSEnd_FSTStates_SPDMBody { get; set; }
        public string MSSEnd_FSTStates_SPDMSACU { get; set; }
        public string MSSEnd_FSTStates_SPDMArms { get; set; }
        public string MSSEnd_Payloads_SSRMSTipLee { get; set; }
        public string MSSEnd_Payloads_SPDMLee { get; set; }
        public string MSSEnd_Payloads_OTCM1 { get; set; }
        public string MSSEnd_Payloads_OTCM2 { get; set; }
        public string MSSEnd_Payloads_MCAS { get; set; }
        public string MSSEnd_Payloads_EOTP { get; set; }
        public string MSSEnd_Payloads_POA { get; set; }
        public string MSSEnd_SSRMSConfiguration { get; set; }
        public string MSSEnd_SPDMConfiguration { get; set; }
        public Nullable<decimal> MSSEnd_Joints_SSRMS_SR { get; set; }
        public Nullable<decimal> MSSEnd_Joints_SSRMS_SY { get; set; }
        public Nullable<decimal> MSSEnd_Joints_SSRMS_SP { get; set; }
        public Nullable<decimal> MSSEnd_Joints_SSRMS_EP { get; set; }
        public Nullable<decimal> MSSEnd_Joints_SSRMS_WP { get; set; }
        public Nullable<decimal> MSSEnd_Joints_SSRMS_WY { get; set; }
        public Nullable<decimal> MSSEnd_Joints_SSRMS_WR { get; set; }
        public Nullable<decimal> MSSEnd_Joints_SSRMS_SPDMBR { get; set; }
        public Nullable<decimal> MSSEnd_Joints_ARM1_SR { get; set; }
        public Nullable<decimal> MSSEnd_Joints_ARM1_SY { get; set; }
        public Nullable<decimal> MSSEnd_Joints_ARM1_SP { get; set; }
        public Nullable<decimal> MSSEnd_Joints_ARM1_EP { get; set; }
        public Nullable<decimal> MSSEnd_Joints_ARM1_WP { get; set; }
        public Nullable<decimal> MSSEnd_Joints_ARM1_WY { get; set; }
        public Nullable<decimal> MSSEnd_Joints_ARM1_WR { get; set; }
        public Nullable<decimal> MSSEnd_Joints_ARM2_SR { get; set; }
        public Nullable<decimal> MSSEnd_Joints_ARM2_SY { get; set; }
        public Nullable<decimal> MSSEnd_Joints_ARM2_SP { get; set; }
        public Nullable<decimal> MSSEnd_Joints_ARM2_EP { get; set; }
        public Nullable<decimal> MSSEnd_Joints_ARM2_WP { get; set; }
        public Nullable<decimal> MSSEnd_Joints_ARM2_WY { get; set; }
        public Nullable<decimal> MSSEnd_Joints_ARM2_WR { get; set; }
        public Nullable<decimal> MSSEnd_Joints_EOTP { get; set; }
    }
}
